Repository google/earthenterprise, pull requests merged in 2018-12, with the labels that each got.

#1100 New versioning logic using automatically generated build numbers
  earth_enterprise/src/scons/getversion.py
Labels: cla: yes

#1108 Fixes #972: Correct spelling error
  earth_enterprise/src/installer/install_fusion.sh
Labels: cla: yes

#1102 Fixes #200 (using symbolic/soft links instead of hard links)
  docs/geedocs/5.2.5/answer/7160006.html
  earth_enterprise/tutorial/SConstruct
Labels: cla: yes

#1106 Issue #1104 - OpenGEE Build Fails on Centos 7
  earth_enterprise/src/third_party/qt/SConscript
Labels: cla: yes

#1110 Issue #1104 - OpenGEE Build Fails on Centos 7 (#1106)
  earth_enterprise/src/third_party/qt/SConscript
Labels: cla: no

#1112 change tail tag to a less release sounding name
  earth_enterprise/src/scons/getversion.py
Labels: bug, cla: yes

#1116 fix upgrading to non-releasable build
  earth_enterprise/src/scons/getversion.py
Labels: bug, cla: yes

#1117 merge Release 5.2.5
  earth_enterprise/src/scons/getversion.py
Labels: cla: no

#1119 create the gevars file on fusion install too
  earth_enterprise/src/installer/install_fusion.sh
Labels: bug, cla: yes

#1125 fix uninstall logic for gevars
  earth_enterprise/src/installer/uninstall_fusion.sh
  earth_enterprise/src/installer/uninstall_server.sh
Labels: bug, cla: yes

#1126 merge from Release 5.2.5
  earth_enterprise/src/installer/install_fusion.sh
  earth_enterprise/src/installer/uninstall_fusion.sh
  earth_enterprise/src/installer/uninstall_server.sh
Labels: cla: yes

#1107 Fixes #1105: turn world-writable files back into symlinks
  docs/geedocs/5.2.5/answer/7160006.html
  earth_enterprise/rpms/buildSrc/src/main/groovy/GeeDeb.groovy
  earth_enterprise/rpms/buildSrc/src/main/groovy/GeeRpm.groovy
Labels: cla: yes

#1129 Fixes #1105: turn world-writable files back into symlinks (#1107)
  docs/geedocs/5.2.5/answer/7160006.html
  earth_enterprise/rpms/buildSrc/src/main/groovy/GeeDeb.groovy
  earth_enterprise/rpms/buildSrc/src/main/groovy/GeeRpm.groovy
Labels: cla: no

#1123 #1122 Explicitly import Image module from PIL
  earth_enterprise/src/fusion/portableglobe/servers/local_server.py
Labels: cla: yes

#1131 #1130: Add Fusion Memory Usage Tests
  earth_enterprise/docs/developer/BuildSystem.md
  earth_enterprise/rpms/build.gradle
  earth_enterprise/src/SConstruct
  earth_enterprise/src/fusion/SConscript
  earth_enterprise/src/fusion/asset-tests/SConscript
  earth_enterprise/src/fusion/asset-tests/bin/generate_test_asset_xmls.py
  earth_enterprise/src/fusion/asset-tests/include/mem_usage/access_private_variables.hpp
  earth_enterprise/src/fusion/asset-tests/include/mem_usage/asset_function_tester.hpp
  earth_enterprise/src/fusion/asset-tests/include/mem_usage/ostream_tee.hpp
  earth_enterprise/src/fusion/asset-tests/include/mem_usage/path.hpp
  earth_enterprise/src/fusion/asset-tests/include/mem_usage/raster_project_function_tester.hpp
  earth_enterprise/src/fusion/asset-tests/include/mem_usage/resource_usage_info.hpp
  earth_enterprise/src/fusion/asset-tests/include/mem_usage/resources.hpp
  earth_enterprise/src/fusion/asset-tests/include/mem_usage/thread_member_function_tester.hpp
  earth_enterprise/src/fusion/asset-tests/include/mem_usage/utils.hpp
  earth_enterprise/src/fusion/asset-tests/memory-usage-tests/SConscript
  earth_enterprise/src/fusion/asset-tests/memory-usage-tests/dont-leak-memory_resourcetest.cc
  earth_enterprise/src/fusion/asset-tests/memory-usage-tests/leak-memory_resourcetest.cc
  earth_enterprise/src/fusion/asset-tests/memory-usage-tests/run-in-detached-thread_resourcetest.cc
  earth_enterprise/src/fusion/asset-tests/share/generate_test_asset_xmls/templates/RasterProduct/CombinedRP.kia/khasset.xml.j2
  earth_enterprise/src/fusion/asset-tests/share/generate_test_asset_xmls/templates/RasterProduct/CombinedRP.kia/khassetver.xml.j2
  earth_enterprise/src/fusion/asset-tests/share/generate_test_asset_xmls/templates/RasterProduct/khasset.xml.j2
  earth_enterprise/src/fusion/asset-tests/share/generate_test_asset_xmls/templates/RasterProduct/khassetver.xml.j2
  earth_enterprise/src/fusion/asset-tests/share/generate_test_asset_xmls/templates/RasterProduct/source.kisource/khasset.xml.j2
  earth_enterprise/src/fusion/asset-tests/share/generate_test_asset_xmls/templates/RasterProduct/source.kisource/khassetver.xml.j2
  earth_enterprise/src/fusion/asset-tests/share/generate_test_asset_xmls/templates/RasterProject/khasset.xml.j2
  earth_enterprise/src/fusion/asset-tests/share/generate_test_asset_xmls/templates/RasterProject/khassetver.xml.j2
  earth_enterprise/src/fusion/autoingest/SConscript
  earth_enterprise/src/fusion/autoingest/memory-tests/SConscript
  earth_enterprise/src/fusion/autoingest/memory-tests/add-to-asset-cache_resourcetest.cc
  earth_enterprise/src/fusion/autoingest/memory-tests/add-to-asset-version-cache_resourcetest.cc
  earth_enterprise/src/fusion/autoingest/memory-tests/load-raster-project-asset-version-from-xml_resourcetest.cc
  earth_enterprise/src/fusion/autoingest/memory-tests/parse-raster-project-xml_resourcetest.cc
  earth_enterprise/src/fusion/autoingest/sysman/SConscript
  earth_enterprise/src/fusion/autoingest/sysman/memory-tests/SConscript
  earth_enterprise/src/fusion/autoingest/sysman/memory-tests/build-raster-project_resourcetest.cc
  earth_enterprise/src/fusion/autoingest/sysman/parse-raster-project-xml-no-content_unittest/SConscript
  earth_enterprise/src/fusion/autoingest/sysman/parse-raster-project-xml-no-content_unittest/parse-raster-project-xml-no-content_unittest.cc
  earth_enterprise/src/scons/khEnvironment.py
  earth_enterprise/src/third_party/SConscript
  earth_enterprise/src/third_party/date/SConscript
  earth_enterprise/third_party/date/BUILD
  earth_enterprise/third_party/date/LICENSE
  earth_enterprise/third_party/date/README.md
  earth_enterprise/third_party/date/v2.4.1.tar.gz
Labels: cla: yes

#1141 move master to version 5.3.0
  earth_enterprise/BUILD.md
  earth_enterprise/Upgrade.md
  earth_enterprise/src/fusion/portableglobe/cutter/cgi-bin/geecheck_tests/common.py
  earth_enterprise/src/fusion_version.txt
  earth_enterprise/src/support/geecheck/geecheck.pl
Labels: cla: yes
