Repository google/earthenterprise, pull requests merged in 2019-07, with the labels that each got.

#1286 Limit cache sizes based on memory usage
  earth_enterprise/src/common/CacheSizeCalculations.h
  earth_enterprise/src/common/khCache.h
  earth_enterprise/src/common/khMetaData.h
  earth_enterprise/src/common/khRefCounter.h
  earth_enterprise/src/fusion/autoingest/Asset.h
  earth_enterprise/src/fusion/autoingest/AssetHandle.h
  earth_enterprise/src/fusion/autoingest/AssetStorage.idl
  earth_enterprise/src/fusion/autoingest/AssetVersion.h
  earth_enterprise/src/fusion/autoingest/MiscConfigStorage.idl
  earth_enterprise/src/fusion/autoingest/StorageManager.h
  earth_enterprise/src/fusion/autoingest/StorageManager_unittest.cpp
  earth_enterprise/src/fusion/autoingest/TaskLists.idl
  earth_enterprise/src/fusion/autoingest/memory-tests/SConscript
  earth_enterprise/src/fusion/autoingest/sysman/AssetHandleD.h
  earth_enterprise/src/fusion/autoingest/sysman/khAssetManager.cpp
  earth_enterprise/src/fusion/autoingest/sysman/khResourceManager.cpp
  earth_enterprise/src/fusion/autoingest/tools/SConscript
  earth_enterprise/src/fusion/autoingest/tools/getop.cpp
  earth_enterprise/src/fusion/gst/gstEarthStream.cpp
  earth_enterprise/src/fusion/gst/gstGeode.h
  earth_enterprise/src/fusion/gst/gstGeometry.h
  earth_enterprise/src/fusion/khraster/CachedRasterInsetReader.h
  earth_enterprise/src/fusion/khraster/ProductLevelReaderCache.h
  earth_enterprise/src/fusion/rasterfuse/ReaderCache.h
  earth_enterprise/src/fusion/rasterfuse/TmeshPackgenTraverser.h
Labels: cla: yes

#1359 Cache Limiting Docs Update
  docs/geedocs/5.3.2/answer/176738.html
Labels: cla: yes

#1362 Added Issue #1281 to release notes
  docs/_data/versions.yml
  docs/geedocs/5.3.2/answer/7160009.html
  docs/geedocs/5.3.2/index.html
Labels: cla: yes

#1368 Fix 1211: Copy download_tutorial.sh instead of link
  earth_enterprise/tutorial/SConstruct
Labels: cla: yes

#1364 Clean and Validate KML Pasted in Cutter
  earth_enterprise/src/fusion/portableglobe/cutter/cgi-bin/globe_cutter_app.py
  earth_enterprise/src/fusion/portableglobe/cutter/htdocs/cutter/js/drawing_tools.js
Labels: cla: yes

#1357 Using and documenting correct FQDN config for issue 1132
  docs/geedocs/5.3.2/answer/4492599.html
  docs/geedocs/5.3.2/answer/HostnameFqdnConfiguration.html
  earth_enterprise/src/server/wsgi/common/geAbstractionFetcher.py
  earth_enterprise/src/server/wsgi/common/utils.py
Labels: cla: yes

#1369 Update release notes for Issue 1132 hostname bug
  docs/geedocs/5.3.2/answer/7160009.html
Labels: cla: yes

#1363 migration from khRefGuard to std::shared_ptr
  earth_enterprise/src/common/SConscript
  earth_enterprise/src/common/khCache.h
  earth_enterprise/src/common/khRefCounter.h
  earth_enterprise/src/fusion/autoingest/Asset.h
  earth_enterprise/src/fusion/autoingest/AssetGenDaemonCpp.pl
  earth_enterprise/src/fusion/autoingest/AssetGenDaemonH.pl
  earth_enterprise/src/fusion/autoingest/AssetGenPublicCpp.pl
  earth_enterprise/src/fusion/autoingest/AssetGenPublicH.pl
  earth_enterprise/src/fusion/autoingest/AssetHandle.h
  earth_enterprise/src/fusion/autoingest/AssetVersion.h
  earth_enterprise/src/fusion/autoingest/FromStorageGen.pl
  earth_enterprise/src/fusion/autoingest/LoadAnyGen.pl
  earth_enterprise/src/fusion/autoingest/StorageManager.h
  earth_enterprise/src/fusion/autoingest/StorageManager_unittest.cpp
  earth_enterprise/src/fusion/autoingest/memory-tests/parse-raster-project-xml_resourcetest.cc
  earth_enterprise/src/fusion/autoingest/sysman/AssetD.cpp
  earth_enterprise/src/fusion/autoingest/sysman/AssetD.h
  earth_enterprise/src/fusion/autoingest/sysman/AssetHandleD.h
  earth_enterprise/src/fusion/autoingest/sysman/AssetVersionD.cpp
  earth_enterprise/src/fusion/autoingest/sysman/AssetVersionD.h
  earth_enterprise/src/fusion/autoingest/sysman/parse-raster-project-xml-no-content_unittest/parse-raster-project-xml-no-content_unittest.cc
Labels: cla: yes

#1334 Resume using graph operations
  .travis.yml
  earth_enterprise/BUILD_RHEL_CentOS.md
  earth_enterprise/BUILD_Ubuntu.md
  earth_enterprise/src/SConstruct
  earth_enterprise/src/fusion/autoingest/Asset.h
  earth_enterprise/src/fusion/autoingest/AssetGenDaemonCpp.pl
  earth_enterprise/src/fusion/autoingest/AssetHandle.h
  earth_enterprise/src/fusion/autoingest/AssetVersion.h
  earth_enterprise/src/fusion/autoingest/MiscConfigStorage.idl
  earth_enterprise/src/fusion/autoingest/StorageManager.h
  earth_enterprise/src/fusion/autoingest/StorageManager_unittest.cpp
  earth_enterprise/src/fusion/autoingest/plugins.src/CombinedRP.src
  earth_enterprise/src/fusion/autoingest/plugins.src/Database.src
  earth_enterprise/src/fusion/autoingest/plugins.src/MercatorRasterProject.src
  earth_enterprise/src/fusion/autoingest/plugins.src/RasterProject.src
  earth_enterprise/src/fusion/autoingest/storage/AssetDefs.idl
  earth_enterprise/src/fusion/autoingest/sysman/AssetHandleD.h
  earth_enterprise/src/fusion/autoingest/sysman/AssetOperation.cpp
  earth_enterprise/src/fusion/autoingest/sysman/AssetOperation.h
  earth_enterprise/src/fusion/autoingest/sysman/AssetVersionD.cpp
  earth_enterprise/src/fusion/autoingest/sysman/AssetVersionD.h
  earth_enterprise/src/fusion/autoingest/sysman/SConscript
  earth_enterprise/src/fusion/autoingest/sysman/StateUpdater.cpp
  earth_enterprise/src/fusion/autoingest/sysman/StateUpdater.h
  earth_enterprise/src/fusion/autoingest/sysman/StateUpdater_unittest.cpp
  earth_enterprise/src/fusion/autoingest/sysman/khAssetManager.cpp
  earth_enterprise/src/fusion/autoingest/sysman/memory-tests/SConscript
  earth_enterprise/src/fusion/autoingest/sysman/parse-raster-project-xml-no-content_unittest/SConscript
Labels: cla: yes

#1374 Update docs resume
  docs/geedocs/5.3.2/answer/176738.html
Labels: cla: no

#1330 refactor overlap calculation code
  docs/geedocs/5.3.2/answer/176738.html
  earth_enterprise/src/common/khInsetCoverage.h
  earth_enterprise/src/fusion/autoingest/AssetGenDaemonCpp.pl
  earth_enterprise/src/fusion/autoingest/AssetGenDaemonH.pl
  earth_enterprise/src/fusion/autoingest/MiscConfigStorage.idl
  earth_enterprise/src/fusion/autoingest/plugins.src/MercatorRasterProject.src
  earth_enterprise/src/fusion/autoingest/plugins.src/PacketGen.src
  earth_enterprise/src/fusion/autoingest/plugins.src/RasterProject.src
  earth_enterprise/src/fusion/autoingest/sysman/InsetInfo.cpp
  earth_enterprise/src/fusion/autoingest/sysman/InsetInfo.h
Labels: cla: no

#1375 Unit tests for new Resume code
  earth_enterprise/src/common/CacheSizeCalculations.h
  earth_enterprise/src/fusion/autoingest/Asset.h
  earth_enterprise/src/fusion/autoingest/AssetHandle.h
  earth_enterprise/src/fusion/autoingest/AssetVersion.h
  earth_enterprise/src/fusion/autoingest/FromStorageGen.pl
  earth_enterprise/src/fusion/autoingest/SConscript
  earth_enterprise/src/fusion/autoingest/StorageManager.h
  earth_enterprise/src/fusion/autoingest/StorageManagerAssetHandle.h
  earth_enterprise/src/fusion/autoingest/StorageManagerAssetHandle_unittest.cpp
  earth_enterprise/src/fusion/autoingest/StorageManager_unittest.cpp
  earth_enterprise/src/fusion/autoingest/sysman/AssetHandleD.h
  earth_enterprise/src/fusion/autoingest/sysman/AssetVersionD.h
  earth_enterprise/src/fusion/autoingest/sysman/StateUpdater.cpp
  earth_enterprise/src/fusion/autoingest/sysman/StateUpdater.h
  earth_enterprise/src/fusion/autoingest/sysman/StateUpdater_unittest.cpp
Labels: cla: yes

#1366 Release notes update for 5.3.1
  docs/geedocs/5.3.1/answer/7160008.html
Labels: cla: yes, documentation

#1382 Updated Release notes to document known issue #1381
  docs/geedocs/5.3.1/answer/7160008.html
Labels: cla: yes

#1383 Merging 5.3.1 branch into master
  docs/geedocs/5.3.1/answer/7160008.html
Labels: cla: yes

#1380 fixes issue #1379 by exempting protobuf-py build commands from cache
  earth_enterprise/src/google/protobuf-py/SConscript
Labels: cla: yes
