Repository google/earthenterprise, pull requests merged in 2019-04, with the labels that each got.

#1254 fix version in docs index file
  docs/geedocs/5.3.0/index.html
Labels: cla: yes

#1252 Move build number to release rpm
  docs/geedocs/5.3.0/answer/7160007.html
  earth_enterprise/rpms/build.gradle
Labels: bug, cla: yes

#1256 #1255 - Limits internal version string to 3 parts to fix patch releases
  earth_enterprise/src/scons/getversion.py
Labels: cla: yes

#1260 Issue #1255 - Limits internal version string to 3 parts - Merge to master
  earth_enterprise/src/scons/getversion.py
Labels: cla: yes

#1261 Merging in Release 5.3.0
  docs/geedocs/5.3.0/answer/7160007.html
  docs/geedocs/5.3.0/index.html
  earth_enterprise/rpms/build.gradle
Labels: cla: yes

#1232 Copy uninstall scripts
  earth_enterprise/SConstruct
  earth_enterprise/src/installer/install_fusion.sh
  earth_enterprise/src/installer/install_server.sh
  earth_enterprise/src/scons/khEnvironment.py
Labels: cla: no

#1245 Resolve issue #798 - investigate Qt build performance
  earth_enterprise/src/third_party/qt/SConscript
Labels: cla: yes

#1269 1192 update openjpeg to 2.3.1
  docs/geedocs/5.3.0/answer/7160007.html
  earth_enterprise/src/third_party/gdal/SConscript
  earth_enterprise/src/third_party/gdal/gdal-jp2-V2.3.1.patch
  earth_enterprise/src/third_party/openjpeg/SConscript
  earth_enterprise/third_party/openjpeg/openjpeg-2.3.0.tar.gz
  earth_enterprise/third_party/openjpeg/openjpeg-2.3.1.tar.gz
Labels: cla: yes

#1271 1270 Fix xml parsing in common.sh
  docs/geedocs/5.3.0/answer/7160007.html
  earth_enterprise/src/installer/common.sh
Labels: cla: yes

#1278 Merge in latest Release 5.3.0 fixes
  docs/geedocs/5.3.0/answer/7160007.html
  earth_enterprise/BUILD_Ubuntu.md
  earth_enterprise/src/installer/common.sh
  earth_enterprise/src/third_party/gdal/SConscript
  earth_enterprise/src/third_party/gdal/gdal-jp2-V2.3.1.patch
  earth_enterprise/src/third_party/openjpeg/SConscript
  earth_enterprise/third_party/openjpeg/openjpeg-2.3.0.tar.gz
  earth_enterprise/third_party/openjpeg/openjpeg-2.3.1.tar.gz
Labels: cla: no

#1280 1279 Fix getversion.py for Windows and update OpenGEE copyright year.
  earth_enterprise/src/fusion/portableglobe/servers/local/preview/developers/terms.html
  earth_enterprise/src/fusion/portableglobe/servers/local/preview/setup.html
  earth_enterprise/src/scons/getversion.py
Labels: cla: yes

#1267 I1258 b update release notes
  docs/geedocs/5.3.0/answer/7160007.html
Labels: cla: yes

#1262 Issue #303: Made uninstallation scripts documentation updates in 5.3.1 directory
  docs/geedocs/5.3.1/answer/3499964.html
  docs/geedocs/5.3.1/answer/4492617.html
  docs/geedocs/5.3.1/answer/7160008.html
Labels: cla: yes

#1285 Update from Release 5.3.0
  docs/geedocs/5.3.0/answer/7160007.html
  earth_enterprise/src/fusion/portableglobe/servers/local/preview/developers/terms.html
  earth_enterprise/src/fusion/portableglobe/servers/local/preview/setup.html
  earth_enterprise/src/scons/getversion.py
Labels: cla: no

#1250 WIP - Parallel build index
  earth_enterprise/src/common/khCache.h
  earth_enterprise/src/common/khMTTypes.h
  earth_enterprise/src/common/khxml/khdom.h
  earth_enterprise/src/fusion/autoingest/Asset.h
  earth_enterprise/src/fusion/autoingest/AssetHandle.h
  earth_enterprise/src/fusion/autoingest/AssetStorage.idl
  earth_enterprise/src/fusion/autoingest/AssetVersion.cpp
  earth_enterprise/src/fusion/autoingest/AssetVersion.h
  earth_enterprise/src/fusion/autoingest/MiscConfigStorage.idl
  earth_enterprise/src/fusion/autoingest/plugins.src/CombinedRP.src
  earth_enterprise/src/fusion/autoingest/plugins.src/Database.src
  earth_enterprise/src/fusion/autoingest/plugins.src/MapLayer.src
  earth_enterprise/src/fusion/autoingest/plugins.src/MapPOI.src
  earth_enterprise/src/fusion/autoingest/plugins.src/MercatorRasterProject.src
  earth_enterprise/src/fusion/autoingest/plugins.src/PacketLevel.src
  earth_enterprise/src/fusion/autoingest/plugins.src/ProjectedMapLayer.src
  earth_enterprise/src/fusion/autoingest/plugins.src/ProjectedMapProject.src
  earth_enterprise/src/fusion/autoingest/plugins.src/RasterProject.src
  earth_enterprise/src/fusion/autoingest/plugins.src/VectorGEIndex.src
  earth_enterprise/src/fusion/autoingest/sysman/AssetHandleD.h
  earth_enterprise/src/fusion/autoingest/sysman/AssetVersionD.cpp
  earth_enterprise/src/fusion/autoingest/sysman/AssetVersionD.h
  earth_enterprise/src/fusion/autoingest/sysman/SConscript
  earth_enterprise/src/fusion/autoingest/sysman/khAssetManager.cpp
  earth_enterprise/src/fusion/autoingest/tools/gefindfilesonvol.cpp
  earth_enterprise/src/fusion/autoingest/tools/gequery.cpp
  earth_enterprise/src/fusion/fusionui/AssetVersionProperties.cpp
Labels: cla: no

#1288 BuildIndex log progress
  earth_enterprise/src/fusion/autoingest/plugins.src/RasterProject.src
Labels: cla: yes
